### ISSUE TITLE
Fix hardcoded value in cape-dict-file

### ISSUE THREAD

**Issue by solna86** [minad/cape#131]
Thanks for creating many useful Emacs packages.

I note the variable `cape-dict-file` is initialized to `"/usr/share/dict/words"`.

Emacs has the variable `ispell-alternate-dictionary`, which tries to guess the dictionary location.

Would it be perhaps more adequate to initialize `cape-dict-file` to the value of `ispell-alternate-dictionary`?

**Comment by minad** [comment]
Hi! Thanks for the suggestion. I absolutely want to avoid loading Ispell, since I consider it obsolete. I've even created an [alternative spell checking package](https://github.com/minad/jinx). We could however duplicate the initialization code from `ispell-alternate-dictionary`. But then I don't think that would be sufficiently useful. My recommendation is to configure the dictionary in your user configuration. You can even set `cape-dict-file` to a function returning a dictionary corresponding to the the language of the buffer.
