### ISSUE TITLE
Add cape-yasnipet

### ISSUE THREAD

**Issue by Crandel** [minad/cape#17]
Thank you @minad for such a nice project!
Is it possible to add cape-yasnipet completion function? Company-yasnippet is built-in into company-mode and I want to skip installing whole package only for this functionality.

**Comment by minad** [comment]
Thanks! 

`cape-yasnippet` is out of scope of Cape since it depends on a third-party package. Maybe someone will create a `yasnippet-capf` package at some point? In the meantime you can either use `consult-yasnippet` if you use Consult or you can install Company and use `company-yasnippet` via the `cape-company-to-capf` adapter. 

If you are interested in digging a bit deeper, you can also take the file `company-yasnippet.el` and remove the company dependency (remove all calls to company functions). This is actually easy to do since there are not many such calls and the existing ones can be replaced with builtins. After having done that you will end up with a company-style backend (which still uses the Company API) but without company dependency which you can use with the `cape-company-to-capf` adapter. In the next step and if you haven't lost interested by then you could convert the API from the Company API to the default Capf API. Then we would end up with a `yasnippet-capf` backend which could be packaged up and distributed separately. 

Please let me know if you have further questions.

**Comment by Crandel** [comment]
Thank you for quick response. I will definitely try consult-yasnippet as I use consult a lot.

**Comment by minad** [comment]
I saw the thread on reddit and created https://github.com/minad/tempel. It is not yasnippet but at least it is simple :)

**Comment by Crandel** [comment]
Looks promising, I will try it

**Comment by maikol-solis** [comment]
This package/script works reasonably nice 

https://github.com/elken/cape-yasnippet
