### ISSUE TITLE
Question: usage with buffer local CAPFs

### ISSUE THREAD

**Issue by andreyorst** [minad/cape#24]
Hi. Thanks for a great package!

I have a small usability question, that raised when I've migrated from Company.
Company has its own notion of backends, which works independently from the `completion-at-point-functions` variable, which is suggested to be modified when using this package. However, there are a lot of other packages, that also modify this variable, by making it buffer-local via a hook. This results in the fact that manually added capes are absent after loading such a module.

In my particular example, I care about `cape-file` and `cape-dabbrev` backends, so I add those to `completion-at-point-functions` with a `prog-mode` hook. Then, when I open, say, a Clojure file, and start a CIDER session, [CIDER calls `add-hook`](https://github.com/clojure-emacs/cider/blob/502b5210cc77f0bbbbea72517f75c0fef7754cec/cider-mode.el#L1057) with optional argument `local` set to `t`. This changes the globally set variable to a locally set one, that contains only the backend set by CIDER. This can be migrated, if I also use buffer-local hooks, then the value keeps backend added by me, and a CIDER backend. But it doesn't work always.

Other examples involve the LSP mode package and Sly/SLIME. LSP-mode, for instance, [kills every other backend and installs its own](https://github.com/emacs-lsp/lsp-mode/blob/b21c70d15ef1cc0c1787ce9faf641ef479a4af0e/lsp-completion.el#L755-L756). Sly [does a similar thing](https://github.com/joaotavora/sly/blob/6669067eea1f63c3c9e6c34ac8d453be76774f6c/lib/sly-completion.el#L353-L354). I understand, that both LSP mode and Sly are trying to provide IDE-like completion experience, but this makes it harder to set cape backends reliably. Company-mode avoided this by using its own notion of backends, though I do understand that this is out of the scope of Cape and Corfu.

This describes the situation. I'm juggling between mode-specific hooks to automatically add needed backends, and default local hooks for all modes that don't modify the variable. This works, but a bit clunky. Any suggestions, on better management of cape backends?

**Comment by minad** [comment]
We don't have to look so far, this even applies to all the usual builtins like `emacs-lisp-mode`. There the `completion-at-point-functions` has the buffer-local value `(elisp-completion-at-point t)`. This mean that first `elisp-completion-at-point` is tried and due to the `t` the global `completion-at-point-functions` are tried afterwards. If we register the `cape-*` capfs globally then they are tried afterwards. Therefore in elisp mode the cape-capfs only trigger when completing within comments or string literals. This is the intended behavior.

If packages override the `completion-at-point-functions` locally in a different way, e.g., by setting it to only `(cider-completion-at-point)` you have to fix this on a case by case basis by adding a function to the respective `*-mode-hook`.

~~~ elisp
(add-hook 'cider-mode-hook
  (lambda () (setq-local completion-at-point-functions '(cider-completion-at-point t))))
~~~

Furthermore sometimes Capfs are too aggressive and always take over even if they don't return candidates. Then one should mark the Capf as non-exclusive. In my opinion all Capfs should be non-exclusive (all Cape capfs are non exclusive) but in reality almost no Capf is non-exclusive. We can also modify this easily:

~~~ elisp
(add-hook 'cider-mode-hook
  (lambda ()
    (setq-local completion-at-point-functions 
      (list (cape-capf-properties #'cider-completion-at-point :exclusive 'no) t)))
~~~

So overall we have a lot of flexibility and all these issues can be solved, but it requires configuration on a case by case basis. Ideally we document such setups in the [Corfu wiki](https://github.com/minad/corfu/wiki), to help other users who want to migrate. By documenting multiple such setups we show the common pattern. I would appreciate if you contribute there if you figure out a good setup which works for you with Slime/Cider etc. Does this answer your question?

**Comment by andreyorst** [comment]
> Does this answer your question?

Yes, thanks for the detailed answer.

> This mean that first `elisp-completion-at-point` is tried and due to the `t` the global `completion-at-point-functions` are tried afterwards.

I wasn't aware of this. Perhaps because nothing usually sits in the global `completion-at-point-functions` in my setup, except for the default `tags-completion-at-point-function` which never worked, as I don't use tags. I guess, when I've tried setting cape capfs as a global value it didn't work because other capfs were non-exclusive, as you've mentioned. But I never knew about this property either. This explains everything.

> Ideally we document such setups in the [Corfu wiki](https://github.com/minad/corfu/wiki), to help other users who want to migrate. By documenting multiple such setups we show the common pattern. I would appreciate if you contribute there if you figure out a good setup which works for you with Slime/Cider

Of course. I'll play around with this new information, and once everything settles in my config for some time, I'll add this to the wiki.

Thanks again!

**Comment by minad** [comment]
> I guess, when I've tried setting cape capfs as a global value it didn't work because other capfs were non-exclusive, as you've mentioned.

Be careful about this! I doubt that this is the issue in most scenarios! Exclusive has a very specific meaning. It means if a Capf returns a completion table, which does not match the input, then it will prevent the other Capfs from running. Non-exclusive means that such a non-matching completion table is then ignored and the next Capf is tried. This means an exclusive Capf can still behave non-exclusively by not returning a completion table at all (and returning nil instead) in situations where it does not trigger. The `elisp-completion-at-point-function` works in that way for example. It is exclusive but sufficiently non-exclusive ;-)
Therefore imo one should just do away with the distinction and treat everything as non-exclusive, but it is usually hard to fix such  historical mistakes in Emacs later on. 

Generally, be careful about these Cape transformers provided by this package. You should only apply them in specific scenarios, where you are sure that they fix the exact problem. For example Cape comes with transformers/wrappers which are specifically made to fix shell completion, see https://github.com/minad/corfu#completing-with-corfu-in-the-shell-or-eshell.
