### ISSUE TITLE
company-bibtex

### ISSUE THREAD

**Issue by mclearc** [minad/cape#30]
I'm trying to get [company-bibtex](https://github.com/gbgar/company-bibtex) working with `cape-company-to-capf` but so far have been unsuccessful (this is likely entirely my fault). Here's my config for `company-bibtex`:

```emacs-lisp
(use-package company-bibtex
  :bind (("<C-tab>" . company-bibtex))
  :after corfu
  :config
  ;; use with corfu/cape
  (setq-local completion-at-point-functions
              (mapcar #'cape-company-to-capf
                      (list #'company-bibtex)))
  (setq company-bibtex-bibliography cpm-bibliography)
  (setq company-bibtex-org-citation-regex "-?@"))
```

This doesn't seem to work unless I call `company-mode` (and then it works via company and not corfu....). Any help is appreciated.

**Comment by minad** [comment]
It ist wrong to bind company-bibtex to a key. You have to define instead:

```elisp
(defalias 'bibtex-capf (cape-interactive-capf (cape-company-to-capf 'company-bibtex)))
```
And bind that to a key.

**Comment by minad** [comment]
@mclearc Did you consider porting `company-bibtex` to the Capf API? This is generally the best way forward in particular for relatively simple backends like this bibtex backend, since it would help most users in the long term. Of course `cape-company-to-capf` is always a viable stop gap measure, but from what I've seen it can be avoided in most cases with little effort. 

There are few sophisticated package like `company-coq` or `purescript-ide` which come with more complex Company backends. For such complex packages porting to Capf is more work. Furthermore it does not seem to be a good idea in those cases to creating completing packages or forks.

**Comment by mclearc** [comment]
Thanks so much -- that worked perfectly. Agreed that a port seems like a good idea here. If I can find the time I'll do so and put a link here. But thanks for the great stop-gap solution!

**Comment by mclearc** [comment]
FYI: this should be helpful for those looking for a replacement for company-bibtex....

https://github.com/mclear-tools/citar-capf
